### ISSUE TITLE
How to analysis for surface sampling?

### ISSUE THREAD

**Issue by HlG4399** [1iyiwei/noise#2]
Hello, I am a graduate student at the Xiamen University, Xiamen, China. I'm interested in your paper, Differential Domain Analysis for Non-uniform Sampling. However, I have some questions after reading.

I want love to know how to analysis for surface sampling? Because I could't find the surface part.
At first I thought it was to use Rui’s code to output a pfm file.

But the result is so bad, such a method is restricted to uniform surface sampling and can suffer from numerical computation issues that limit the maximum number of allowable samples to only a few hundred.Maybe it's because I don't learn much that these problems are relatively simple.

Thank you for your patience, and I look forward to hearing from you.

**Comment by 1iyiwei** [comment]
Rui Wang wrote the surface part of the code http://graphics.cs.umass.edu/pubs/nonuniform-analysis.zip; please ask him related questions. Thanks.

**Comment by HlG4399** [comment]
Thank you for your reply! I will try the code later, thank you again for your patience!
